### ekf config file ###
ekf_node:
    ros__parameters:
        frequency: 25.0

        two_d_mode: false

        publish_acceleration: true
        publish_tf: true
        
        map_frame: map
        odom_frame: odom
        base_link_frame: base_link
        world_frame: odom

        # x, y, z, 
        # roll, pitch, yaw, 
        # vx, vy, vz, 
        # vroll, vpitch, vyaw, 
        # ax, ay, az
        odom0: odom
        odom0_config: [false, false, false,
                       false, false, false,
                       true, true, false,
                       false, false, true,
                       false, false, false]

        imu0: imu_data
        imu0_config: [false, false, false,
                      false, false, false,
                      false, false, false,
                      false, false, true,
                      false, false, false]